SAMPLER_CONFIG = {
    "gemma-4-26b-a4b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "gemma-4-e4b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "gemma-4-e2b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "gemma-4-31b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "mistral-small-4-119b": {
        "temp": "0.1",
        "min-p": "0.0",
        "chat-template-kwargs": '{"reasoning_effort": "none"}',
    },
    "ministral-3-3b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-3b-reasoning": {
        "temp": "0.7",
        "min-p": "0.0",
    },
    "ministral-3-8b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-8b-reasoning": {
        "temp": "0.7",
        "min-p": "0.0",
    },
    "ministral-3-14b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-14b-reasoning": {
        "temp": "1.0",
        "min-p": "0.0",
    },
    "qwen3.5-0.8b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.5-2b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.5-4b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.5-9b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.6-35b-a3b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true, "preserve_thinking": true}',
    },
    "qwen3-coder-next-80b": {
        "temp": "1.0",
        "top-k": "40",
        "min-p": "0.01",
    },
    "glm-4.7-flash": {
        "temp": "1.0",
        "min-p": "0.0",
        "jinja": "true",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.5-122b-a10b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.5-27b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "chat-template-kwargs": '{"enable_thinking": true}',
    },
    "qwen3.6-27b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "chat-template-kwargs": '{"enable_thinking": true, "preserve_thinking": true}',
    },
    "gpt-oss-120b": {
        "temp": "1.0",
        "top-p": "1.0",
        "top-k": "0",
        "min-p": "0.0",
        "ubatch-size": "2048",
        "jinja": "true",
        "chat-template-kwargs": '{"reasoning_effort": "high"}',
    },
    "gpt-oss-20b": {
        "temp": "1.0",
        "top-p": "1.0",
        "top-k": "0",
        "min-p": "0.0",
        "ubatch-size": "2048",
        "jinja": "true",
        "chat-template-kwargs": '{"reasoning_effort": "high"}',
    },
}

FAMILY_DESCRIPTIONS = {
    "gemma-4-26b-a4b": "Gemma 4 26B A4B",
    "gemma-4-e4b": "Gemma 4 E4B",
    "gemma-4-e2b": "Gemma 4 E2B",
    "gemma-4-31b": "Gemma 4 31B",
    "mistral-small-4-119b": "Mistral Small 4 119B",
    "ministral-3-3b-instruct": "Ministral 3 3B Instruct",
    "ministral-3-3b-reasoning": "Ministral 3 3B Reasoning",
    "ministral-3-8b-instruct": "Ministral 3 8B Instruct",
    "ministral-3-8b-reasoning": "Ministral 3 8B Reasoning",
    "ministral-3-14b-instruct": "Ministral 3 14B Instruct",
    "ministral-3-14b-reasoning": "Ministral 3 14B Reasoning",
    "qwen3.5-0.8b": "Qwen3.5 0.8B",
    "qwen3.5-2b": "Qwen3.5 2B",
    "qwen3.5-4b": "Qwen3.5 4B",
    "qwen3.5-9b": "Qwen3.5 9B",
    "qwen3.5-27b": "Qwen3.5 27B",
    "qwen3.6-35b-a3b": "Qwen3.6 35B A3B",
    "qwen3.6-27b": "Qwen3.6 27B",
    "qwen3-coder-next-80b": "Qwen3 Coder Next 80B",
    "glm-4.7-flash": "GLM 4.7 Flash",
    "qwen3.5-122b-a10b": "Qwen3.5 122B A10B",
    "gpt-oss-120b": "GPT-OSS 120B",
    "gpt-oss-20b": "GPT-OSS 20B",
}
