SAMPLER_CONFIG = {
    "gemma-4-26b-a4b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "reasoning": "on",
    },
    "gemma-4-e4b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "reasoning": "on",
    },
    "gemma-4-e2b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "reasoning": "on",
    },
    "gemma-4-31b": {
        "temp": "1.0",
        "top-k": "64",
        "min-p": "0.0",
        "reasoning": "on",
    },
    "mistral-small-4-119b": {
        "temp": "0.1",
        "min-p": "0.0",
        "chat-template-kwargs": '{"reasoning_effort": "none"}',
    },
    "ministral-3-3b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-3b-reasoning": {
        "temp": "0.7",
        "min-p": "0.0",
    },
    "ministral-3-8b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-8b-reasoning": {
        "temp": "0.7",
        "min-p": "0.0",
    },
    "ministral-3-14b-instruct": {
        "temp": "0.1",
        "min-p": "0.0",
    },
    "ministral-3-14b-reasoning": {
        "temp": "1.0",
        "min-p": "0.0",
    },
    "qwen3.5-0.8b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "reasoning": "on",
    },
    "qwen3.5-2b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "reasoning": "on",
    },
    "qwen3.5-4b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "reasoning": "on",
    },
    "qwen3.5-9b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "reasoning": "on",
    },
    "qwen3.6-35b-a3b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "reasoning": "on",
        "chat-template-kwargs": '{"preserve_thinking": true}',
    },
    "qwen3-coder-next-80b": {
        "temp": "1.0",
        "top-k": "40",
        "min-p": "0.01",
    },
    "glm-4.7-flash": {
        "temp": "1.0",
        "min-p": "0.0",
        "jinja": "true",
        "reasoning": "on",
    },
    "qwen3.5-122b-a10b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "reasoning": "on",
    },
    "qwen3.5-27b": {
        "temp": "1.0",
        "top-k": "20",
        "min-p": "0.0",
        "presence-penalty": "1.5",
        "reasoning": "on",
    },
    "qwen3.6-27b": {
        "temp": "0.6",
        "top-k": "20",
        "min-p": "0.0",
        "reasoning": "on",
        "chat-template-kwargs": '{"preserve_thinking": true}',
    },
    "gpt-oss-120b": {
        "temp": "1.0",
        "top-p": "1.0",
        "top-k": "0",
        "min-p": "0.0",
        "ubatch-size": "2048",
        "jinja": "true",
        "chat-template-kwargs": '{"reasoning_effort": "high"}',
    },
    "gpt-oss-20b": {
        "temp": "1.0",
        "top-p": "1.0",
        "top-k": "0",
        "min-p": "0.0",
        "ubatch-size": "2048",
        "jinja": "true",
        "chat-template-kwargs": '{"reasoning_effort": "high"}',
    },
}
